'use strict';
var sourceData = [
  {
    title:       'Story Book',
    category:   'web',
    imgsrc:      '',
    author:    'Siamak Broomand',
    publishedOn: '',
    problem:        '<p>problem </p>',
    methodsUsed: '<p>used methods</p>',
    githubUrl:   'https://amphib24.github.io/storybook-project/story.html',
  },
  {
    title:       'Salmon cookies',
    category:   'wowwww',
    imgsrc:      '',
    author:      'Siamak Broomand',
    publishedOn: '',
    problem:        '<p></p>',
    methodsUsed: '<p></p>',
    githubUrl:   '',
  },
  {
    title:       'My Portfolio',
    category:   'web',
    imgsrc:      '',
    author:      'Siamak Broomand',
    publishedOn: '',
    problem:        '<p></p>',
    methodsUsed: '<p></p>',
    githubUrl:   '',
  },
  {
    title:       'Bus Mall',
    category:   'whaaaat',
    imgsrc:      '',
    author:      '',
    publishedOn: '',
    problem:        '<p></p>',
    methodsUsed: '<p></p>',
    githubUrl:   '',
  },
];
