'use strict';
var sourceData = [
  {
    title:       'Story Book',
    category:   'web',
    imgsrc:      '',
    author:    'Siamak Broomand',
    publishedOn: '',
    mission:        '<p>Mission: <br>To make a website in which <strong> kids </strong> can either type or ask their parents to type the story they tell based on the photo shown.  This is basically designed to <em> avoid repetition </em> of bedtime stories and most important of all to make kids <strong> creative </strong>.  </p>',
    methodsUsed: '<p>used methods</p>',
    githubUrl:   'https://amphib24.github.io/storybook-project/story.html',
  },
  {
    title:       'Salmon cookies',
    category:   'wowwww',
    imgsrc:      '',
    author:      'Siamak Broomand',
    publishedOn: '',
    mission:        '<p></p>',
    methodsUsed: '<p></p>',
    githubUrl:   '',
  },
  {
    title:       'My Portfolio',
    category:   'web',
    imgsrc:      '',
    author:      'Siamak Broomand',
    publishedOn: '',
    mission:        '<p></p>',
    methodsUsed: '<p></p>',
    githubUrl:   '',
  },
  {
    title:       'Bus Mall',
    category:   'whaaaat',
    imgsrc:      '',
    author:      '',
    publishedOn: '',
    mission:        '<p></p>',
    methodsUsed: '<p></p>',
    githubUrl:   '',
  },
];
